apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubevirt.io/hostpath-provisioner
    volume.kubernetes.io/selected-node: microshift.example.com
  name: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: kubevirt-hostpath-provisioner
  volumeMode: Filesystem

