apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: docker.io/karve/sensehat-dotnet
        securityContext:
          privileged: true

