---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
spec:
  #storageClassName: "kubevirt-hostpath-provisioner"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/hpvolumes/grafana"
...
