---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  annotations:
    kubevirt.io/provisionOnNode: coreos
spec:
  storageClassName: kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
...

