apiVersion: v1
kind: Pod
metadata:
  labels:
    run: notebook
  name: notebook
spec:
  initContainers:
  - name: pull-xray
    image: docker.io/alpine/git
    command: ["git", "clone", "https://github.com/tbaums/ml-sandbox.git", "/data/ml-sandbox"]
    #command: ["git", "clone", "https://github.com/rh-aiservices-bu/licence-plate-workshop.git", "/data"]
    volumeMounts:
    - name: volume-name
      mountPath: /data
  containers:
  - image: docker.io/karve/tensorflow-notebook:arm64
    #imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
  #- image: docker.io/jupyter/scipy-notebook:latest
    name: pod
    # mysecretpassword
    args: ["jupyter", "notebook", "--port", "5001", "--no-browser", "--ip=*", "--NotebookApp.token=", "--NotebookApp.password=sha1:d6941d783443:9f33baf62756660be91b606f0fdf1b57b6d3c6fa"]
    volumeMounts:
    - name: volume-name
      mountPath: /home/jovyan/work
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  #volumes:
  #  - name: volume-name
  #    emptyDir: {}
  volumes:
    - name: volume-name
      persistentVolumeClaim:
        claimName: xray-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: notebook
  name: flask-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: notebook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: notebook
  name: notebook-svc
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: notebook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    run: notebook
  name: notebook-route
spec:
  host: notebook-route-default.cluster.local
  port:
    targetPort: 5001
  to:
    kind: Service
    name: notebook-svc
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    run: notebook
  name: flask-route
spec:
  host: flask-route-default.cluster.local
  port:
    targetPort: 5000
  to:
    kind: Service
    name: notebook-svc
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xray-pvc
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: xray-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xray-pv
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/hpvolumes/xray"

