apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
spec:
  runtimeClassName: kata
  containers:
  - name: busybox-1
    image: busybox:latest
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
