---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-provisioner-claim
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
...

