---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noderedpvc
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: noderedpv
...

