---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: noderedpv
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/hpvolumes/nodered"
...
