apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensehat-deployment
spec:
  selector:
    matchLabels:
      app: sensehat
  replicas: 1
  template:
    metadata:
      labels:
        app: sensehat
    spec:
      containers:
      - name: sensehat
        image: docker.io/karve/sensehat
        imagePullPolicy: Always
        #command: ["/bin/bash","-c","sleep infinity"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        # resource required for hpa
        resources:
          requests:
            memory: 128M
            cpu: 125m
          limits:
            memory: 1024M
            cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
 name: sensehat-svc
 labels:
   app: sensehat
spec:
 type: NodePort
 ports:
 - port: 8080
   nodePort: 30080
 selector:
   app: sensehat

