apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongodb-writers.demo.karve.com
spec:
  group: demo.karve.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["table", "name", "age", "country"]
              properties:
                table:
                  type: string
                name:
                  type: string
                age:
                  type: integer
                country:
                  type: string
  scope: Namespaced
  names:
    plural: mongodb-writers
    singular: mongodb-writer
    kind: MongodbWriter
    shortNames:
    - msw
