apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-upload-dv
  annotations:
    kubevirt.io/provisionOnNode: microshift.example.com
spec:
  source:
    upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: kubevirt-hostpath-provisioner
    volumeMode: Filesystem

