---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
spec:
  #storageClassName: "kubevirt-hostpath-provisioner"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/hpvolumes/influxdb"
...
